/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package thor

import org.junit.runner.RunWith
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class CustomerIDTest extends AnyFlatSpec with Matchers {
  behavior of "customer"

  it can "be extracted to name" in {
    val CustomerID(name) = "name--1234"
    name shouldBe "name"
  }

  it should "throw MatchError with invalid name" in {
    intercept[MatchError] {
      val CustomerID(_) = "invalid name"
    }
  }
}
